### PR TITLE
Add Ecma 402 part of the spec

### PR DESCRIPTION
**Pull request by jessealama**
We don't currently envirion Decimal128 objects as
primitives, so we can't rely on `ToPrimitive` to work.

### CODE REVIEW

**Review by ptomato — COMMENTED** [review]
When you copy an abstract operation that already exists, it's customary to mark the parts that changed with `<ins>` and `<del>` tags - these show up in the rendering as green-background and struck-out text, respectively.

Also it might be convenient for rendering to have everything in one HTML file — if you want that, you can do `<emu-import href="intl-spec.emu"></emu-import>` in the main EMU file.

**Review by littledan — COMMENTED** [review]
Wasn't there going to be a part of the Intl integration that makes NumberFormat use the Decimal's own precision (ie length of trailing zeroes) by default?

**Comment by sffc** [comment]
+1, this handles the ToIntlMathematicalValue but it should preserve the Decimal's precision. The following should "just work"

```javascript
new Intl.NumberFormat("en").format(new Decimal("500.00"))
// should return "500.00"
```

**Comment by jessealama** [comment]
I guess the task is to convert some ambient contextual information for the number of desired fractional digits (min & max) into an options bag for a call to `toString`. I think that can be done. We can make that example work. Where is that information available, though?

**Comment by jessealama** [comment]
I'm closing this issue for now in favor of discussing things first on [an Ecma 402 call](https://github.com/tc39/ecma402/issues/856). The list of open tasks here is wide open, so a PR is premature.

**Pull request closed without merging**
